export interface LanguagesData {
  CODE: string;
  NAME: string;
}

export const languages: LanguagesData[] = [
  { CODE: "af-ZA", NAME: "Afrikaans - South Africa" },
  { CODE: "sq-AL", NAME: "Albanian - Albania" },
  { CODE: "ar-DZ", NAME: "Arabic - Algeria" },
  { CODE: "ar-BH", NAME: "Arabic - Bahrain" },
  { CODE: "ar-EG", NAME: "Arabic - Egypt" },
  { CODE: "ar-IQ", NAME: "Arabic - Iraq" },
  { CODE: "ar-JO", NAME: "Arabic - Jordan" },
  { CODE: "ar-KW", NAME: "Arabic - Kuwait" },
  { CODE: "ar-LB", NAME: "Arabic - Lebanon" },
  { CODE: "ar-LY", NAME: "Arabic - Libya" },
  { CODE: "ar-MA", NAME: "Arabic - Morocco" },
  { CODE: "ar-OM", NAME: "Arabic - Oman" },
  { CODE: "ar-QA", NAME: "Arabic - Qatar" },
  { CODE: "ar-SA", NAME: "Arabic - Saudi Arabia" },
  { CODE: "ar-SY", NAME: "Arabic - Syria" },
  { CODE: "ar-TN", NAME: "Arabic - Tunisia" },
  { CODE: "ar-AE", NAME: "Arabic - United Arab Emirates" },
  { CODE: "ar-YE", NAME: "Arabic - Yemen" },
  { CODE: "hy-AM", NAME: "Armenian - Armenia" },
  { CODE: "eu-ES", NAME: "Basque - Basque" },
  { CODE: "be-BY", NAME: "Belarusian - Belarus" },
  { CODE: "bg-BG", NAME: "Bulgarian - Bulgaria" },
  { CODE: "ca-ES", NAME: "Catalan - Catalan" },
  { CODE: "zh-CN", NAME: "Chinese - China" },
  { CODE: "zh-HK", NAME: "Chinese - Hong Kong SAR" },
  { CODE: "zh-MO", NAME: "Chinese - Macau SAR" },
  { CODE: "zh-SG", NAME: "Chinese - Singapore" },
  { CODE: "zh-TW", NAME: "Chinese - Taiwan" },
  { CODE: "hr-HR", NAME: "Croatian - Croatia" },
  { CODE: "cs-CZ", NAME: "Czech - Czech Republic" },
  { CODE: "da-DK", NAME: "Danish - Denmark" },
  { CODE: "div-MV", NAME: "Dhivehi - Maldives" },
  { CODE: "nl-BE", NAME: "Dutch - Belgium" },
  { CODE: "nl-NL", NAME: "Dutch - The Netherlands" },
  { CODE: "en-AU", NAME: "English - Australia" },
  { CODE: "en-BZ", NAME: "English - Belize" },
  { CODE: "en-CA", NAME: "English - Canada" },
  { CODE: "en-CB", NAME: "English - Caribbean" },
  { CODE: "en-IE", NAME: "English - Ireland" },
  { CODE: "en-JM", NAME: "English - Jamaica" },
  { CODE: "en-NZ", NAME: "English - New Zealand" },
  { CODE: "en-ZA", NAME: "English - South Africa" },
  { CODE: "en-TT", NAME: "English - Trinidad and Tobago" },
  { CODE: "en-GB", NAME: "English - United Kingdom" },
  { CODE: "en-US", NAME: "English - United States" },
  { CODE: "en-PH", NAME: "English - Philippines" },
  { CODE: "en-ZW", NAME: "English - Zimbabwe" },
  { CODE: "et-EE", NAME: "Estonian - Estonia" },
  { CODE: "fo-FO", NAME: "Faroese - Faroe Islands" },
  { CODE: "fa-IR", NAME: "Farsi - Iran" },
  { CODE: "fi-FI", NAME: "Finnish - Finland" },
  { CODE: "fr-BE", NAME: "French - Belgium" },
  { CODE: "fr-CA", NAME: "French - Canada" },
  { CODE: "fr-FR", NAME: "French - France" },
  { CODE: "fr-LU", NAME: "French - Luxembourg" },
  { CODE: "fr-MC", NAME: "French - Monaco" },
  { CODE: "fr-CH", NAME: "French - Switzerland" },
  { CODE: "gl-ES", NAME: "Galician - Galician" },
  { CODE: "ka-GE", NAME: "Georgian - Georgia" },
  { CODE: "de-AT", NAME: "German - Austria" },
  { CODE: "de-DE", NAME: "German - Germany" },
  { CODE: "de-LI", NAME: "German - Liechtenstein" },
  { CODE: "de-LU", NAME: "German - Luxembourg" },
  { CODE: "de-CH", NAME: "German - Switzerland" },
  { CODE: "el-GR", NAME: "Greek - Greece" },
  { CODE: "gu-IN", NAME: "Gujarati - India" },
  { CODE: "he-IL", NAME: "Hebrew - Israel" },
  { CODE: "hi-IN", NAME: "Hindi - India" },
  { CODE: "en-IN", NAME: "English - India" },
  { CODE: "hu-HU", NAME: "Hungarian - Hungary" },
  { CODE: "is-IS", NAME: "Icelandic - Iceland" },
  { CODE: "id-ID", NAME: "Indonesian - Indonesia" },
  { CODE: "it-IT", NAME: "Italian - Italy" },
  { CODE: "it-CH", NAME: "Italian - Switzerland" },
  { CODE: "ja-JP", NAME: "Japanese - Japan" },
  { CODE: "kn-IN", NAME: "Kannada - India" },
  { CODE: "kk-KZ", NAME: "Kazakh - Kazakhstan" },
  { CODE: "kok-IN", NAME: "Konkani - India" },
  { CODE: "ko-KR", NAME: "Korean - Korea" },
  { CODE: "ky-KZ", NAME: "Kyrgyz - Kazakhstan" },
  { CODE: "lv-LV", NAME: "Latvian - Latvia" },
  { CODE: "lt-LT", NAME: "Lithuanian - Lithuania" },
  { CODE: "mk-MK", NAME: "Macedonian (FYROM)" },
  { CODE: "ms-BN", NAME: "Malay - Brunei" },
  { CODE: "ms-MY", NAME: "Malay - Malaysia" },
  { CODE: "mr-IN", NAME: "Marathi - India" },
  { CODE: "mn-MN", NAME: "Mongolian - Mongolia" },
  { CODE: "nb-NO", NAME: "Norwegian (Bokm l) - Norway" },
  { CODE: "nn-NO", NAME: "Norwegian (Nynorsk) - Norway" },
  { CODE: "pl-PL", NAME: "Polish - Poland" },
  { CODE: "pt-BR", NAME: "Portuguese - Brazil" },
  { CODE: "pt-PT", NAME: "Portuguese - Portugal" },
  { CODE: "pa-IN", NAME: "Punjabi - India" },
  { CODE: "ro-RO", NAME: "Romanian - Romania" },
  { CODE: "ru-RU", NAME: "Russian - Russia" },
  { CODE: "sa-IN", NAME: "Sanskrit - India" },
  { CODE: "sk-SK", NAME: "Slovak - Slovakia" },
  { CODE: "sl-SI", NAME: "Slovenian - Slovenia" },
  { CODE: "es-AR", NAME: "Spanish - Argentina" },
  { CODE: "es-BO", NAME: "Spanish - Bolivia" },
  { CODE: "es-CL", NAME: "Spanish - Chile" },
  { CODE: "es-CO", NAME: "Spanish - Colombia" },
  { CODE: "es-CR", NAME: "Spanish - Costa Rica" },
  { CODE: "es-DO", NAME: "Spanish - Dominican Republic" },
  { CODE: "es-EC", NAME: "Spanish - Ecuadora" },
  { CODE: "es-SV", NAME: "Spanish - El Salvador" },
  { CODE: "es-GT", NAME: "Spanish - Guatemala" },
  { CODE: "es-HN", NAME: "Spanish - Honduras" },
  { CODE: "es-MX", NAME: "Spanish - Mexico" },
  { CODE: "es-NI", NAME: "Spanish - Nicaragua" },
  { CODE: "es-PA", NAME: "Spanish - Panama" },
  { CODE: "es-PY", NAME: "Spanish - Paraguay" },
  { CODE: "es-PE", NAME: "Spanish - Peru" },
  { CODE: "es-PR", NAME: "Spanish - Puerto Rico" },
  { CODE: "es-ES", NAME: "Spanish - Spain" },
  { CODE: "es-UY", NAME: "Spanish - Uruguay" },
  { CODE: "es-VE", NAME: "Spanish - Venezuela" },
  { CODE: "sv-FI", NAME: "Swedish - Finland" },
  { CODE: "sv-SE", NAME: "Swedish - Sweden" },
  { CODE: "syr-SY", NAME: "Syriac - Syria" },
  { CODE: "ta-IN", NAME: "Tamil - India" },
  { CODE: "tt-RU", NAME: "Tatar - Russia" },
  { CODE: "te-IN", NAME: "Telugu - India" },
  { CODE: "th-TH", NAME: "Thai - Thailand" },
  { CODE: "tr-TR", NAME: "Turkish - Turkey" },
  { CODE: "uk-UA", NAME: "Ukrainian - Ukraine" },
  { CODE: "ur-PK", NAME: "Urdu - Pakistan" },
  { CODE: "vi-VN", NAME: "Vietnamese - Vietnam-AL	Albanian - Albania" },
  { CODE: "ar-DZ", NAME: "Arabic - Algeria" },
  { CODE: "ar-BH", NAME: "Arabic - Bahrain" },
  { CODE: "ar-EG", NAME: "Arabic - Egypt" },
  { CODE: "ar-IQ", NAME: "Arabic - Iraq" },
  { CODE: "ar-JO", NAME: "Arabic - Jordan" },
  { CODE: "ar-KW", NAME: "Arabic - Kuwait" },
  { CODE: "ar-LB", NAME: "Arabic - Lebanon" },
  { CODE: "ar-LY", NAME: "Arabic - Libya" },
  { CODE: "ar-MA", NAME: "Arabic - Morocco" },
  { CODE: "ar-OM", NAME: "Arabic - Oman" },
  { CODE: "ar-QA", NAME: "Arabic - Qatar" },
  { CODE: "ar-SA", NAME: "Arabic - Saudi Arabia" },
  { CODE: "ar-SY", NAME: "Arabic - Syria" },
  { CODE: "ar-TN", NAME: "Arabic - Tunisia" },
  { CODE: "ar-AE", NAME: "Arabic - United Arab Emirates" },
  { CODE: "hy-AM", NAME: "Armenian - Armenia" },
  { CODE: "eu-ES", NAME: "Basque - Basque" },
  { CODE: "be-BY", NAME: "Belarusian - Belarus" },
  { CODE: "bg-BG", NAME: "Bulgarian - Bulgaria" },
  { CODE: "ca-ES", NAME: "Catalan - Catalan" },
  { CODE: "zh-CN", NAME: "Chinese - China" },
  { CODE: "zh-HK", NAME: "Chinese - Hong Kong SAR" },
  { CODE: "zh-MO", NAME: "Chinese - Macau SAR" },
  { CODE: "zh-SG", NAME: "Chinese - Singapore" },
  { CODE: "zh-TW", NAME: "Chinese - Taiwan" },
  { CODE: "hr-HR", NAME: "Croatian - Croatia" },
  { CODE: "cs-CZ", NAME: "Czech - Czech Republic" },
  { CODE: "da-DK", NAME: "Danish - Denmark" },
  { CODE: "div-MV", NAME: "Dhivehi - Maldives" },
  { CODE: "nl-BE", NAME: "Dutch - Belgium" },
  { CODE: "nl-NL", NAME: "Dutch - The Netherlands" },
  { CODE: "en-AU", NAME: "English - Australia" },
  { CODE: "en-BZ", NAME: "English - Belize" },
  { CODE: "en-CA", NAME: "English - Canada" },
  { CODE: "en-CB", NAME: "English - Caribbean" },
  { CODE: "en-IE", NAME: "English - Ireland" },
  { CODE: "en-JM", NAME: "English - Jamaica" },
  { CODE: "en-NZ", NAME: "English - New Zealand" },
  { CODE: "en-PH", NAME: "English - Philippines" },
  { CODE: "en-ZA", NAME: "English - South Africa" },
  { CODE: "en-TT", NAME: "English - Trinidad and Tobago" },
  { CODE: "en-GB", NAME: "English - United Kingdom" },
  { CODE: "en-US", NAME: "English - United States" },
  { CODE: "en-ZW", NAME: "English - Zimbabwe" },
  { CODE: "et-EE", NAME: "Estonian - Estonia" },
  { CODE: "fo-FO", NAME: "Faroese - Faroe Islands" },
  { CODE: "fa-IR", NAME: "Farsi - Iran" },
  { CODE: "fi-FI", NAME: "Finnish - Finland" },
  { CODE: "fr-BE", NAME: "French - Belgium" },
  { CODE: "fr-CA", NAME: "French - Canada" },
  { CODE: "fr-FR", NAME: "French - France" },
  { CODE: "fr-LU", NAME: "French - Luxembourg" },
  { CODE: "fr-MC", NAME: "French - Monaco" },
  { CODE: "fr-CH", NAME: "French - Switzerland" },
  { CODE: "gl-ES", NAME: "Galician - Galician" },
  { CODE: "ka-GE", NAME: "Georgian - Georgia" },
  { CODE: "de-AT", NAME: "German - Austria" },
  { CODE: "de-DE", NAME: "German - Germany" },
  { CODE: "de-LI", NAME: "German - Liechtenstein" },
  { CODE: "de-LU", NAME: "German - Luxembourg" },
  { CODE: "de-CH", NAME: "German - Switzerland" },
  { CODE: "el-GR", NAME: "Greek - Greece" },
  { CODE: "gu-IN", NAME: "Gujarati - India" },
  { CODE: "he-IL", NAME: "Hebrew - Israel" },
  { CODE: "hi-IN", NAME: "Hindi - India" },
  { CODE: "hu-HU", NAME: "Hungarian - Hungary" },
  { CODE: "is-IS", NAME: "Icelandic - Iceland" },
  { CODE: "id-ID", NAME: "Indonesian - Indonesia" },
  { CODE: "it-IT", NAME: "Italian - Italy" },
  { CODE: "it-CH", NAME: "Italian - Switzerland" },
  { CODE: "ja-JP", NAME: "Japanese - Japan" },
  { CODE: "kn-IN", NAME: "Kannada - India" },
  { CODE: "kk-KZ", NAME: "Kazakh - Kazakhstan" },
  { CODE: "kok-IN", NAME: "Konkani - India" },
  { CODE: "ko-KR", NAME: "Korean - Korea" },
  { CODE: "ky-KZ", NAME: "Kyrgyz - Kazakhstan" },
  { CODE: "lv-LV", NAME: "Latvian - Latvia" },
  { CODE: "lt-LT", NAME: "Lithuanian - Lithuania" },
  { CODE: "mk-MK", NAME: "Macedonian (FYROM)" },
  { CODE: "ms-BN", NAME: "Malay - Brunei" },
  { CODE: "ms-MY", NAME: "Malay - Malaysia" },
  { CODE: "mr-IN", NAME: "Marathi - India" },
  { CODE: "mn-MN", NAME: "Mongolian - Mongolia" },
  { CODE: "nb-NO", NAME: "Norwegian (Bokm l) - Norway" },
  { CODE: "nn-NO", NAME: "Norwegian (Nynorsk) - Norway" },
  { CODE: "pl-PL", NAME: "Polish - Poland" },
  { CODE: "pt-PT", NAME: "Portuguese - Portugal" },
  { CODE: "pa-IN", NAME: "Punjabi - India" },
  { CODE: "ro-RO", NAME: "Romanian - Romania" },
  { CODE: "ru-RU", NAME: "Russian - Russia" },
  { CODE: "sa-IN", NAME: "Sanskrit - India" },
  { CODE: "pt-BR", NAME: "Serbian (Cyrillic) - Serbia" },
  { CODE: "sk-SK", NAME: "Slovak - Slovakia" },
  { CODE: "sl-SI", NAME: "Slovenian - Slovenia" },
  { CODE: "es-AR", NAME: "Spanish - Argentina" },
  { CODE: "es-BO", NAME: "Spanish - Bolivia" },
  { CODE: "es-CL", NAME: "Spanish - Chile" },
  { CODE: "es-CO", NAME: "Spanish - Colombia" },
  { CODE: "es-CR", NAME: "Spanish - Costa Rica" },
  { CODE: "es-DO", NAME: "Spanish - Dominican Republic" },
  { CODE: "es-EC", NAME: "Spanish - Ecuador" },
  { CODE: "es-SV", NAME: "Spanish - El Salvador" },
  { CODE: "es-GT", NAME: "Spanish - Guatemala" },
  { CODE: "es-HN", NAME: "Spanish - Honduras" },
  { CODE: "es-MX", NAME: "Spanish - Mexico" },
  { CODE: "es-NI", NAME: "Spanish - Nicaragua" },
  { CODE: "es-PA", NAME: "Spanish - Panama" },
  { CODE: "es-PY", NAME: "Spanish - Paraguay" },
  { CODE: "es-PE", NAME: "Spanish - Peru" },
  { CODE: "es-PR", NAME: "Spanish - Spanish - Puerto Rico" },
  { CODE: "es-ES", NAME: "Spanish - Spain" },
  { CODE: "es-UY", NAME: "Spanish - Uruguay" },
  { CODE: "es-VE", NAME: "Spanish - Venezuela" },
  { CODE: "sw-KE", NAME: "Swahili - Kenya" },
  { CODE: "sv-FI", NAME: "Swedish - Finland" },
  { CODE: "sv-SE", NAME: "Swedish - Sweden" },
  { CODE: "syr-SY", NAME: "Syriac - Syria" },
  { CODE: "ta-IN", NAME: "Tamil - India" },
  { CODE: "tt-RU", NAME: "Tatar - Russia" },
  { CODE: "te-IN", NAME: "Telugu - India" },
  { CODE: "th-TH", NAME: "Thai - Thailand" },
  { CODE: "tr-TR", NAME: "Turkish - Turkey" },
  { CODE: "uk-UA", NAME: "Ukrainian - Ukraine" },
  { CODE: "ur-PK", NAME: "Urdu - Pakistan" },
  { CODE: "vi-VN", NAME: "Vietnamese - Vietnam" },
];

export const translationLanguages = [
  { CODE: "en", NAME: "English" },
  { CODE: "es", NAME: "Español" },
];
