import { EnvContext } from "../components/providers/EnvProvider";
import { useContext } from "react";
export const useEnv = () => {
  const { env } = useContext(EnvContext);
  return {
    ...env,
    NEXT_PUBLIC_LEADMANAGER_ENDPOINT: env.VITE_LEADMANAGER_ENDPOINT,
    NEXT_PUBLIC_USERHUB_ENDPOINT: env.VITE_USERHUB_ENDPOINT,
    NEXT_PUBLIC_MEETANDNOTE_ENDPOINT: env.VITE_MEETANDNOTE_ENDPOINT,
    NEXT_PUBLIC_PROPOSAL_ENDPOINT: env.VITE_PROPOSAL_ENDPOINT,
    NEXT_PUBLIC_AECPOSTMAN_ENDPOINT: env.VITE_AECPOSTMAN_ENDPOINT,
    NEXT_PUBLIC_PROCUREMENT_ENDPOINT: env.VITE_PROCUREMENT_ENDPOINT,
    NEXT_PUBLIC_PAYMASTER_ENDPOINT: env.VITE_PAYMASTER_ENDPOINT,
    NEXT_PUBLIC_APIKEY: env.VITE_APIKEY,
    NEXT_PUBLIC_ACCESS_KEY: env.VITE_ACCESS_KEY,
    NEXT_PUBLIC_INTOAEC_LOGO: env.VITE_INTOAEC_LOGO,
    NEXT_PUBLIC_TERMS_OF_SERVICES_URL: env.VITE_TERMS_OF_SERVICES_URL,
    NEXT_PUBLIC_PRIVACY_POLICY_URL: env.VITE_PRIVACY_POLICY_URL,
    NEXT_PUBLIC_INTOAEC_ORG_EMAIL: env.VITE_INTOAEC_ORG_EMAIL,
    NEXT_PUBLIC_INTOAEC_SALES_EMAIL: env.VITE_INTOAEC_SALES_EMAIL,
    NEXT_PUBLIC_STRIPE_PUBLISH_KEY: env.VITE_STRIPE_PUBLISH_KEY,
  };
};
