import { EnvContext } from "../components/providers/EnvProvider";
import { useContext } from "react";
export const useEnv = () => {
  const { env } = useContext(EnvContext);
  return {
    ...env,
    NEXT_PUBLIC_LEADMANAGER_ENDPOINT: env.VITE_LEADMANAGER_ENDPOINT,
    NEXT_PUBLIC_USERHUB_ENDPOINT: env.VITE_USERHUB_ENDPOINT,
    NEXT_PUBLIC_MEETANDNOTE_ENDPOINT: env.VITE_MEETANDNOTE_ENDPOINT,
    NEXT_PUBLIC_PROPOSAL_ENDPOINT: env.VITE_PROPOSAL_ENDPOINT,
    NEXT_PUBLIC_AECPOSTMAN_ENDPOINT: env.VITE_AECPOSTMAN_ENDPOINT,
    NEXT_PUBLIC_PROCUREMENT_ENDPOINT: env.VITE_PROCUREMENT_ENDPOINT,
    NEXT_PUBLIC_PAYMASTER_ENDPOINT: env.VITE_PAYMASTER_ENDPOINT,
    NEXT_PUBLIC_APIKEY: env.VITE_APIKEY,
  };
};
